<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <WarningsAsErrors>$(WarningsAsErrors);CS8509</WarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AgentTeamForge.DAL/AgentTeamForge.DAL.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="AgentTeamForge.Tests" />
  </ItemGroup>
</Project>
